[15.0][ADD] project_mis_report_budget_margin
solvosci/slv-mis-builder pull request #4
Opened 2024-06-17 07:20 UTC by ChristianSantamaria

Adds in Auto-Create button Budget Margins

2024-06-18 11:10 UTC, ChristianSantamaria commented
@dalonsod Can u review this addon?

2024-06-20 06:51 UTC, dalonsod requested changes
See comments, and also:

- I'd add, as `optional="show"`, `is_margin` field to KPI's tree view within report form.
- A minimum control to `is_margin` should be required. E.g. adding an onchange method that prevent checking a second KPI as margin.

And, at last, is it possible to move this new functionality to `project_mis_report_budget` as a major improvement?

2024-06-20 06:51 UTC, dalonsod commented on project_mis_report_budget_margin/models/project_project.py
> +        budget_id = self.mis_budget_ids.create({
IMO we should always use `self.env[...].create()` instead of calling a field

2024-06-20 06:51 UTC, dalonsod commented on project_mis_report_budget_margin/models/project_project.py
> +                expression_id = self.mis_report_template_id.kpi_ids.filtered(lambda x: x.is_margin).expression_ids[0].id
Better try this:
```suggestion
            margin_kpi_ids = self.mis_report_template_id.kpi_ids.filtered(lambda x: x.is_margin)
            expression_id = margin_kpi_ids and margin_kpi_ids.expression_ids[0].id or False
```

2024-06-21 12:22 UTC, dalonsod reviewed
Only minor comment

2024-06-21 12:22 UTC, dalonsod commented on project_mis_report_budget/models/mis_report_kpi.py
> +        if not self.budgetable:
Both checks should only be made if `is_margin` is `True`

2024-06-24 10:33 UTC, ChristianSantamaria commented
@dalonsod Updated Test enviroment

2024-06-24 14:33 UTC, dalonsod approved these changes
Only code review :+1:

2024-06-24 14:34 UTC, merged