[15.0][IMP+FIX] projec_mis_report, *_budget: some improvements and fix
solvosci/slv-mis-builder pull request #8
Opened 2024-08-07 10:33 UTC by ChristianSantamaria

project_mis_report
- IMP: recalculate report instance: When change project end date recalculate report instance

project_mis_report_budget
- FIX: new calculation to obtain the margin
- IMP: recalculate margin budget - When change project end date recalculate margin budget
- IMP: allow duplicate - In the project.project form you can duplicate budgets

2024-08-07 15:06 UTC, dalonsod requested changes
See comments

2024-08-07 15:06 UTC, dalonsod commented on project_mis_report_budget/models/project_project.py
> +                    expenses -= expense
Why not this (more homogeneous way)?
```suggestion
                past_expenses = sum(budget_ids.item_ids.filtered(lambda x: x.date_to <= record.last_close_date and x.kpi_expression_id.kpi_id.kpi_type == 'expense').mapped('amount'))

                expenses -= past_expenses

```

2024-08-07 15:06 UTC, dalonsod commented on project_mis_report/models/project_project.py
> +        if 'date' in vals and vals['date'] and self.date + relativedelta(months=1) > self.mis_report_instance_id.period_ids[-2].date_to:
Remember that `write()` is multi!!!

2024-08-07 15:06 UTC, dalonsod commented on project_mis_report/models/project_project.py
> +        if 'date' in vals and vals['date'] and self.date + relativedelta(months=1) > self.mis_report_instance_id.period_ids[-2].date_to:
Is it guaranteed that `record.mis_report_instance_id.period_ids` will always have two or more elements?

2024-08-07 15:06 UTC, dalonsod commented on project_mis_report_budget/models/project_project.py
> +            budget_id = self.mis_budget_ids.filtered(lambda x: x.name == '%s - %s' % (self.name, _('MARGINS')))
This is a very weak margins budget identification. E.g. if any user changes budget name before this operation, it won't work. Is it possible to add a technical field for budgets that indicate "Is a Margin Budget" and filter by it, and then create margin budget with such check before?

And, if name is finally used as "filtering" technique, please create a variable first with such value, as used twice (filtering and creating).

2024-08-07 15:06 UTC, dalonsod commented on project_mis_report_budget/models/mis_budget.py
> +        budget_id.state = 'draft'
Please better use built-in method for this:

https://github.com/OCA/mis-builder/blob/8a19a30b6afc3da50fac83143fbed0dcf100a3d5/mis_builder_budget/models/mis_budget_abstract.py#L55

2024-08-08 08:15 UTC, ChristianSantamaria commented on project_mis_report/models/project_project.py
> +        if 'date' in vals and vals['date'] and self.date + relativedelta(months=1) > self.mis_report_instance_id.period_ids[-2].date_to:
Yes, at least it will have 2 elements, which would be the month column, and the total sum column

2024-08-08 11:06 UTC, dalonsod commented on project_mis_report_budget/models/mis_budget.py
> +    is_margin = fields.Boolean()
This field should be readonly, as it shouldn't be filled by users (is a technical field). And, is it possible to be added at least to one view (e.g. custom tree view within projects) and set it visible only in debug mode, for testing purposes?

2024-08-12 16:11 UTC, dalonsod approved these changes
In fact, approved by LR. Let's merge....

2024-08-12 16:11 UTC, merged